version: "3"
services:

  integration_tests:
    image: iae94/calendar_integration_tests
    container_name: "calendar_integration_tests"
    depends_on:
      - psql
      - rabbit
      - api
      - scheduler
      - notificator
  api:
    image: iae94/calendar_api
    container_name: "calendar_api"
    ports:
      - "50051:50051"
    depends_on:
      - psql
  notificator:
    image: iae94/calendar_notificator
    container_name: "calendar_notificator"
    depends_on:
      - rabbit
      - psql
  scheduler:
    image: iae94/calendar_scheduler
    container_name: "calendar_scheduler"
    depends_on:
      - rabbit
      - psql
  psql:
    image: iae94/calendar_psql
    #image: psql
    container_name: "postgres-calendar"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Calendar
  rabbit:
    image: rabbitmq:3-management-alpine
    working_dir: /app
    hostname: rabbit-calendar
    container_name: 'rabbit-calendar'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: my_vhost
volumes:
  my_data: