FROM golang:alpine

RUN apk update && apk upgrade && apk add --no-cache bash git openssh gcc

COPY /calendar /go/src/calendar
WORKDIR /go/src/calendar/pkg/integration_tests/

ENV CGO_ENABLED=0
ENV GO111MODULE=on
RUN go mod download

CMD ["go", "test", "-v"]